apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js-sample
  template:
    metadata:
      labels:
        app: node-js-sample
    spec:
      containers:
      - name: node-js-sample
        image: anupsharma329/node:v2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-js-sample-service
spec:
  type: NodePort
  selector:
    app: node-js-sample
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000